# Generated by Django 4.1.2 on 2022-11-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_internal',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
