# Generated by Django 4.0.6 on 2022-07-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='base_currency_type',
            field=models.CharField(choices=[('UAH', 'Hrivna'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('BTC', 'BitCoin')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.CharField(choices=[('UAH', 'Hrivna'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('BTC', 'BitCoin')], max_length=3),
        ),
    ]
