# Generated by Django 4.0.6 on 2022-07-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='todo',
        ),
    ]
